### ISSUE TITLE
Pattern view not working

### ISSUE THREAD

**Issue by blcham** [owlcs/OPPL2#4]
Hi,

I am trying to run OPPL2 pattern plugin with Protege_4.3. I was not able to compile version in "master" branch, thus i used version from tag "oppl2-parent-2.1.0".

 Unfortunately it does not work due to following issues.

1) oppl2plugin/src/main/resources/plugin.xml has bad reference to classes, which can be easily fixed :
    org.coode.patterns.ui.PatternOntologyView ----> org.coode.patterns.protege.ui.PatternOntologyView 
    org.coode.patterns.ui.PatternOntologyView ---> org.coode.patterns.protege.ui.PatternOntologyView   
   
2) after fixing 1) it throws following exception (maybe incorrect OWLAPI version ?):
java.lang.NoSuchMethodError: org.semanticweb.owlapi.model.IRI.getNamespace()Ljava/lang/String;
        at org.coode.oppl.OPPLShortFormProvider.getShortForm(OPPLShortFormProvider.java:18)
        at org.semanticweb.owlapi.util.BidirectionalShortFormProviderAdapter.generateShortForm(BidirectionalShortFormProviderAdapter.java:126)
        at org.semanticweb.owlapi.util.CachingBidirectionalShortFormProvider.add(CachingBidirectionalShortFormProvider.java:120)
        at org.coode.oppl.OPPLFactory.defaultEntityChecker(OPPLFactory.java:76)
        at org.coode.oppl.OPPLFactory.<init>(OPPLFactory.java:68)
    
Thank you.

**Comment by ignazio1977** [comment]
Both assumptions are correct: the class names were wrong and the OWLAPI version in Protege 4.3 is 3.4.2 by default; OPPL is using 3.4.10, in version 2.1.0.

I've fixed both and I'll be releasing version 3.0.0 soon.
